 2017-10-17 10:47:45,139 [P12528/D2/T1] INFO  Umbraco.Core.CoreBootManager - Umbraco 7.6.3 application starting on MIMERSBRUNN01
 2017-10-17 10:47:45,162 [P12528/D2/T1] INFO  Umbraco.Core.PluginManager - Determining hash of code files on disk
 2017-10-17 10:47:45,179 [P12528/D2/T1] INFO  Umbraco.Core.PluginManager - Hash determined (took 17ms)
 2017-10-17 10:47:45,255 [P12528/D2/T1] INFO  Umbraco.Core.MainDom - Acquiring MainDom...
 2017-10-17 10:47:45,257 [P12528/D2/T1] INFO  Umbraco.Core.MainDom - Acquired MainDom.
 2017-10-17 10:47:45,260 [P12528/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2017-10-17 10:47:45,698 [P12528/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 438ms)
 2017-10-17 10:47:45,699 [P12528/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IApplicationStartupHandler
 2017-10-17 10:47:45,706 [P12528/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IApplicationStartupHandler (took 7ms)
 2017-10-17 10:47:45,726 [P12528/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2017-10-17 10:47:45,727 [P12528/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2017-10-17 10:47:45,727 [P12528/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IPropertyEditorValueConverter
 2017-10-17 10:47:45,744 [P12528/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IPropertyEditorValueConverter (took 16ms)
 2017-10-17 10:47:45,745 [P12528/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2017-10-17 10:47:45,745 [P12528/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2017-10-17 10:47:45,745 [P12528/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IPropertyValueConverter
 2017-10-17 10:47:45,753 [P12528/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IPropertyValueConverter (took 7ms)
 2017-10-17 10:47:45,769 [P12528/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2017-10-17 10:47:45,770 [P12528/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2017-10-17 10:47:45,770 [P12528/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.Mvc.SurfaceController
 2017-10-17 10:47:45,777 [P12528/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.Mvc.SurfaceController (took 7ms)
 2017-10-17 10:47:45,778 [P12528/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2017-10-17 10:47:45,778 [P12528/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2017-10-17 10:47:45,779 [P12528/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.WebApi.UmbracoApiController
 2017-10-17 10:47:45,785 [P12528/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.WebApi.UmbracoApiController (took 6ms)
 2017-10-17 10:47:47,358 [P12528/D2/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: |DataDirectory|\Umbraco.sdf. Exception: System.Data.SqlServerCe.SqlCeException (0x80004005): The database file cannot be found. Check the path to the database. [ Data Source = C:\Users\Admin\Source\Repos\jakobsdal\JakobsdalUmbraco\App_Data\Umbraco.sdf ]
   vid System.Data.SqlServerCe.SqlCeConnection.Open(Boolean silent)
   vid System.Data.SqlServerCe.SqlCeConnection.Open()
   vid Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
 2017-10-17 10:47:47,364 [P12528/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2017-10-17 10:47:47,426 [P12528/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.Models.PublishedContent.PublishedContentModel
 2017-10-17 10:47:47,437 [P12528/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.Models.PublishedContent.PublishedContentModel (took 11ms)
 2017-10-17 10:47:47,540 [P12528/D2/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: |DataDirectory|\Umbraco.sdf. Exception: System.Data.SqlServerCe.SqlCeException (0x80004005): The database file cannot be found. Check the path to the database. [ Data Source = C:\Users\Admin\Source\Repos\jakobsdal\JakobsdalUmbraco\App_Data\Umbraco.sdf ]
   vid System.Data.SqlServerCe.SqlCeConnection.Open(Boolean silent)
   vid System.Data.SqlServerCe.SqlCeConnection.Open()
   vid Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
 2017-10-17 10:47:47,541 [P12528/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2017-10-17 10:47:48,574 [P12528/D2/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: |DataDirectory|\Umbraco.sdf. Exception: System.Data.SqlServerCe.SqlCeException (0x80004005): The database file cannot be found. Check the path to the database. [ Data Source = C:\Users\Admin\Source\Repos\jakobsdal\JakobsdalUmbraco\App_Data\Umbraco.sdf ]
   vid System.Data.SqlServerCe.SqlCeConnection.Open(Boolean silent)
   vid System.Data.SqlServerCe.SqlCeConnection.Open()
   vid Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
 2017-10-17 10:47:48,575 [P12528/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2017-10-17 10:47:49,611 [P12528/D2/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: |DataDirectory|\Umbraco.sdf. Exception: System.Data.SqlServerCe.SqlCeException (0x80004005): The database file cannot be found. Check the path to the database. [ Data Source = C:\Users\Admin\Source\Repos\jakobsdal\JakobsdalUmbraco\App_Data\Umbraco.sdf ]
   vid System.Data.SqlServerCe.SqlCeConnection.Open(Boolean silent)
   vid System.Data.SqlServerCe.SqlCeConnection.Open()
   vid Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
 2017-10-17 10:47:49,616 [P12528/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2017-10-17 10:47:50,652 [P12528/D2/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: |DataDirectory|\Umbraco.sdf. Exception: System.Data.SqlServerCe.SqlCeException (0x80004005): The database file cannot be found. Check the path to the database. [ Data Source = C:\Users\Admin\Source\Repos\jakobsdal\JakobsdalUmbraco\App_Data\Umbraco.sdf ]
   vid System.Data.SqlServerCe.SqlCeConnection.Open(Boolean silent)
   vid System.Data.SqlServerCe.SqlCeConnection.Open()
   vid Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
 2017-10-17 10:47:50,653 [P12528/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2017-10-17 10:47:51,687 [P12528/D2/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: |DataDirectory|\Umbraco.sdf. Exception: System.Data.SqlServerCe.SqlCeException (0x80004005): The database file cannot be found. Check the path to the database. [ Data Source = C:\Users\Admin\Source\Repos\jakobsdal\JakobsdalUmbraco\App_Data\Umbraco.sdf ]
   vid System.Data.SqlServerCe.SqlCeConnection.Open(Boolean silent)
   vid System.Data.SqlServerCe.SqlCeConnection.Open()
   vid Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
 2017-10-17 10:47:51,688 [P12528/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2017-10-17 10:47:52,721 [P12528/D2/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: |DataDirectory|\Umbraco.sdf. Exception: System.Data.SqlServerCe.SqlCeException (0x80004005): The database file cannot be found. Check the path to the database. [ Data Source = C:\Users\Admin\Source\Repos\jakobsdal\JakobsdalUmbraco\App_Data\Umbraco.sdf ]
   vid System.Data.SqlServerCe.SqlCeConnection.Open(Boolean silent)
   vid System.Data.SqlServerCe.SqlCeConnection.Open()
   vid Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
 2017-10-17 10:47:52,722 [P12528/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2017-10-17 10:47:52,725 [P12528/D2/T1] ERROR Umbraco.Core.UmbracoApplicationBase - An unhandled exception occurred
Umbraco.Core.Exceptions.UmbracoStartupFailedException: Umbraco cannot start. A connection string is configured but Umbraco cannot connect to the database.
   vid Umbraco.Core.CoreBootManager.EnsureDatabaseConnection()
   vid Umbraco.Core.CoreBootManager.Complete(Action`1 afterComplete)
   vid Umbraco.Web.WebBootManager.Complete(Action`1 afterComplete)
   vid Umbraco.Core.UmbracoApplicationBase.StartApplication(Object sender, EventArgs e)
   vid Umbraco.Core.UmbracoApplicationBase.Application_Start(Object sender, EventArgs e)
 2017-10-17 10:48:02,869 [P12528/D2/T7] ERROR UmbracoExamine.DataServices.UmbracoContentService - EXCEPTION OCCURRED reading GetAllUserPropertyNames
System.Data.SqlServerCe.SqlCeException (0x80004005): The database file cannot be found. Check the path to the database. [ Data Source = C:\Users\Admin\Source\Repos\jakobsdal\JakobsdalUmbraco\App_Data\Umbraco.sdf ]
   vid System.Data.SqlServerCe.SqlCeConnection.Open(Boolean silent)
   vid System.Data.SqlServerCe.SqlCeConnection.Open()
   vid Umbraco.Core.Persistence.FaultHandling.RetryPolicy.<>c__DisplayClass1.<ExecuteAction>b__0()
   vid Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   vid Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction(Action action)
   vid Umbraco.Core.Persistence.PetaPocoConnectionExtensions.OpenWithRetry(IDbConnection connection, RetryPolicy retryPolicy)
   vid Umbraco.Core.Persistence.PetaPocoConnectionExtensions.OpenWithRetry(IDbConnection connection)
   vid Umbraco.Core.Persistence.Database.OpenSharedConnection()
   vid Umbraco.Core.Persistence.Database.BeginTransaction(IsolationLevel isolationLevel)
   vid Umbraco.Core.Scoping.Scope.get_Database()
   vid Umbraco.Core.DatabaseContext.get_Database()
   vid UmbracoExamine.DataServices.UmbracoContentService.GetAllUserPropertyNames()
 2017-10-17 10:48:03,103 [P12528/D2/T7] INFO  Umbraco.Core.MainDom - Stopping...
 2017-10-17 10:48:03,103 [P12528/D2/T7] INFO  Umbraco.Core.MainDom - Released MainDom.
 2017-10-17 10:48:33,126 [P12528/D2/T8] INFO  Umbraco.Core.UmbracoApplicationBase - Application shutdown. Details: InitializationError

_shutDownMessage=Initialization Error
HostingEnvironment initiated shutdown
HostingEnvironment orsakade avslut

_shutDownStack=   vid System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   vid System.Environment.get_StackTrace()
   vid System.Web.Hosting.HostingEnvironment.InitiateShutdownInternal()
   vid System.Web.Hosting.HostingEnvironment.InitiateShutdownWithoutDemand()
   vid System.Web.HttpRuntime.ShutdownAppDomain(String stackTrace)
   vid System.Web.HttpRuntime.AppDomainShutdownTimerCallback(Object state)
   vid System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
   vid System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   vid System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   vid System.Threading.TimerQueueTimer.CallCallback()
   vid System.Threading.TimerQueueTimer.Fire()
   vid System.Threading.TimerQueue.FireNextTimers()
   vid System.Threading.TimerQueue.AppDomainTimerCallback()
